@startuml
'https://plantuml.com/use-case-diagram

:Main Admin: as Admin
(Population) as (Use)

User -> (Start)
User --> (largest city)

Admin ---> (Use)

note right of Admin : cities.

note right of (Use)
A note can also
be on several lines
end note

note "top populated countries." as N
(Start) .. N2
N2 .. (Use)
@enduml